# Note the order is intentional to avoid multiple passes of the hooks
minimum_pre_commit_version: 4.2.0
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb, '10240']
  - id: check-case-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
  - id: check-toml
  - id: check-vcs-permalinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: fix-byte-order-marker
  - id: check-merge-conflict
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix, --no-sort]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.0
  hooks:
  - id: clang-format
    types_or: [c++, c, objective-c, objective-c++]
- repo: local
  hooks:
  - id: rust-fmt
    name: rust fmt
    language: system
    entry: cargo fmt --all --manifest-path Cargo.toml
    types: [rust]
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
