[workspace]
resolver = "2"
members = ["minimal-importer", "minimal-importer-app", "minimal-importer-bundle", "minimal-importer-util", "trivial-ffi-sandbox", "trivial-lifetime-sandbox", "trivial-lifetime-sandbox-mancy"]

[profile.release]
lto = true
codegen-units = 1
